### ISSUE TITLE
Set intersection not working on version 0.2.2

### ISSUE THREAD

**Issue by YPares** [dmwit/ordered-containers#23]
When running:

```
import Data.Set.Ordered

Prelude Data.Set.Ordered> fromList [1,2,4] |/\ fromList [1,2,3]
```

I get:
```
fromList [1,2,4]
```
which clearly isn't the right answer. Also when using `/\|` instead, it's even worse, it loops indefinitely and never returns.

**Comment by RyanGlScott** [comment]
Great find! I believe there are two separate bugs here. The first bug is in the definition of `(|/\)`:

https://github.com/dmwit/ordered-containers/blob/b9e40539042fa6b76c1fa50705497853b5445f0b/Data/Set/Ordered.hs#L165-L168

I think the last line of that function is incorrect, as it is swapping the order of `ts` (the input) rather than `ts''` (which contains the intersection of the two sets).

The second bug, which is more obvious, is in the definition of `(/\|)`:

https://github.com/dmwit/ordered-containers/blob/b9e40539042fa6b76c1fa50705497853b5445f0b/Data/Set/Ordered.hs#L173-L174

This is `flip`ping itself, which explains why it loops. This should probably be `flip (|/\)` instead.

**Comment by YPares** [comment]
Ah, I didn't look at the implementation TBH.

Also I'm not quite sure of the point of having left/right variants for intersection for sets (whereas for maps, yes it makes sense).

**Comment by dmwit** [comment]
Thank you for the report! Should be fixed now 🤞

We could indeed have only `/\`, but then it would be ambiguous which side's indices take precedence, and we already have a naming convention that disambiguates that, so we might as well use it. But then once you have one or the other, say `/\|`, it becomes an obvious API completeness question why you don't have the other `|/\`. So we have both.
